// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TECin2.API.Database;

#nullable disable

namespace TECin2.API.Migrations.TECinContext2Migrations
{
    [DbContext(typeof(TECinContext2))]
    partial class TECinContext2ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TECin2.API.Database.Entities.Password", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Salt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Password");
                });

            modelBuilder.Entity("TECin2.API.Database.Entities.SecurityNumb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("SecurityNumb");
                });
#pragma warning restore 612, 618
        }
    }
}
